version: '3.8'

services:
  chatroom-server:
    build: .
    container_name: chatroom-server
    ports:
      - "8894:8894"
    restart: unless-stopped
    volumes:
      - ./:/app
    command: uvicorn chatroom_server:app --host 0.0.0.0 --port 8894 